live_config_reload = true
import = [
	"~/.config/alacritty/tokyonight_moon.toml"
]

[env]
TERM = "alacritty"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.99
blur = true

[window.padding]
x = 0
y = 0

[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"
