#!/bin/zsh

VAULT_DIR="/Users/metinyalcinkaya/Documents/Obsidian/Main"
SOURCE_DIR="uncategorized"
DEST_DIR="notes"

find "$VAULT_DIR/$SOURCE_DIR" -type f -name "*.md" | while read -r file; do
  echo "Processing $file"
  tag=$(awk '/tags:/{getline; print; exit;}' "$file" | sed -e 's/^ *- *//' -e 's/^ *//;s/ *$//')
  echo "Found tag $tag"
  if [ ! -z "$tag" ]; then
    TARGET_DIR="$VAULT_DIR/$DEST_DIR/$tag"
    mkdir -p "$TARGET_DIR"

    mv "$file" "$TARGET_DIR"
    echo "Moved $file to $TARGET_DIR"
  else
    echo "No tag found for $file"
  fi
done
echo "Done!"
